[tool.poetry]
name = "dts-helper"
version = "0.1.0"
description = "Agentic DPDK DTS Development Assistant"
authors = ["Koushik Bhargav Nimoji <koushiknimoji@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "dts_agents"}]

[tool.poetry.dependencies]
python = "^3.10"
chromadb = "^0.5.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.0"
mypy = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"